apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: elbertsoftware-com-tls
spec:
  secretName: elbertsoftware-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: elbertsoftware.com
  dnsNames:
    - elbertsoftware.com
    - www.elbertsoftware.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - elbertsoftware.com
          - www.elbertsoftware.com
